[versions]
accompanist = "0.34.0"
androidGradlePlugin = "8.7.2"
androidxComposeBom = "2024.11.00"
androidxCore = "1.15.0"
androidMaterial = "1.12.0"
androidxAppCompat = "1.7.0"
androidxActivity = "1.9.3"
graphics = "1.0.1"
constraintLayout = "1.1.0"

androidxLifecycle = "2.8.7"
androidxNavigation = "2.8.4"

androidxEspresso = "3.5.0"
androidxTestExt = "1.1.4"


coil = "2.5.0"

junit4 = "4.13.2"

kotlin = "2.0.20"

coroutines = "1.9.0"
datetime = "0.6.1"
serialization = "1.7.2"
okhttp = "5.0.0-alpha.10"

room = "2.6.1"
ksp = "2.0.20-1.0.25"

youtubedlAndroid = "0.17.1"

mmkv = "1.3.9"

koin = "4.0.0"

ktfmt = "0.20.1"

[libraries]


androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
android-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }

androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }

accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
accompanist-webview = { group = "com.google.accompanist", name = "accompanist-webview", version.ref = "accompanist" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }

#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom-alpha", version.ref = "androidxComposeBom" }

androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }

androidx-compose-material = { group = "androidx.compose.material", name = "material" }

androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }

androidx-graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphics" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout" }

androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }

androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }

androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }


coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }


room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

#youtubedl-android-library = { group = "com.github.yausername.youtubedl_android", name = "library", version.ref = "youtubedlAndroid" }
#youtubedl-android-ffmpeg = { group = "com.github.yausername.youtubedl_android", name = "ffmpeg", version.ref = "youtubedlAndroid" }
#youtubedl-android-aria2c = { group = "com.github.yausername.youtubedl_android", name = "aria2c", version.ref = "youtubedlAndroid" }

youtubedl-android-library = { group = "io.github.junkfood02.youtubedl-android", name = "library", version.ref = "youtubedlAndroid" }
youtubedl-android-ffmpeg = { group = "io.github.junkfood02.youtubedl-android", name = "ffmpeg", version.ref = "youtubedlAndroid" }
youtubedl-android-aria2c = { group = "io.github.junkfood02.youtubedl-android", name = "aria2c", version.ref = "youtubedlAndroid" }

mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ktfmt-gradle = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }


[bundles]
accompanist = [
    "accompanist-permissions",
    "accompanist-webview",
    "accompanist-pager-indicators",
]

androidxCompose = ["androidx-compose-ui",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material-iconsExtended",
    "androidx-compose-material3",
    "androidx-compose-material3-windowSizeClass",
    "androidx-compose-foundation",
    "androidx-navigation-compose",
    "androidx-compose-animation",
    "androidx-constraintlayout-compose"
]

youtubedlAndroid = ["youtubedl-android-library",
    "youtubedl-android-ffmpeg",
    "youtubedl-android-aria2c"]

core = ["androidx-activity-compose",
    "android-material",
    "androidx-appcompat",
    "androidx-core-ktx"]
